services:

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend

    container_name: backend
    environment:
      - DATABASE_URL: postgresql+psycopg2://appuser:apppass@postgres:5432/chatdb
    ports:
      - "8000:8000"

    depends_on:
      - postgres

volumes:
  postgres_data: